[tools]
go = "1.22.0"

[settings]
experimental = true
not_found_auto_install = true

[tasks.deck_build]
description = 'Build the DECK 🎥'
alias = "db"
dir = "deck"
sources = ['deck.md', 'assets/*']
run = "npx @marp-team/marp-cli@latest deck.md;"

[tasks.deck_open]
description = 'Open the DECK 🎥'
alias = "do"
dir = "deck"
run = "open deck.html"

[tasks.init_cluster]
description = 'Initialize the Kubernetes Cluster'
run = """
#kubectl create namespace operator-testing
kubectl create secret docker-registry gcr-json-key \
		--docker-server=australia-southeast2-docker.pkg.dev \
		--docker-username=_json_key \
		--docker-password="$(cat secrets/freyr-operator-b9bde5075a35.json)" \
		-n op-freyr-system
kubectl patch -n op-freyr-system serviceaccount op-freyr-controller-manager -p '{"imagePullSecrets": [{"name": "gcr-json-key"}]}'
kubectl patch -n default serviceaccount default -p '{"imagePullSecrets": [{"name": "gcr-json-key"}]}'
"""