[tools]
go = "1.24.0"

[settings]
experimental = true
not_found_auto_install = true

[tasks.deck_build]
description = 'Build the DECK 🎥'
alias = "db"
dir = "deck"
sources = ['deck.md', 'assets/*']
run = "npx @marp-team/marp-cli@latest deck.md;"

[tasks.deck_open]
description = 'Open the DECK 🎥'
alias = "do"
dir = "deck"
run = "open deck.html"

[tasks.port_captain]
run="kubectl port-forward -n ship-operator deployment/captain 5001:5001;"

[tasks.port_grafana]
run="kubectl port-forward -n telemetry deployment/grafana 3000:3000;"
