apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: dsprometheus
    url: http://prometheus:9090
    isDefault: false
    access: proxy
    editable: true

  - name: Jaeger
    type: jaeger
    uid: dsjaeger
    url: http://jaeger:16686
    isDefault: false
    access: proxy
    editable: true
