# permissions for end users to edit operators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: operator-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: op-freyr
    app.kubernetes.io/part-of: op-freyr
    app.kubernetes.io/managed-by: kustomize
  name: operator-editor-role
rules:
- apiGroups:
  - freyr.fmtl.au
  resources:
  - operators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - freyr.fmtl.au
  resources:
  - operators/status
  verbs:
  - get
