# permissions for end users to edit freyrs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: freyr-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: freyr
    app.kubernetes.io/part-of: freyr
    app.kubernetes.io/managed-by: kustomize
  name: freyr-editor-role
rules:
- apiGroups:
  - freyr.fmtl.au
  resources:
  - freyrs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - freyr.fmtl.au
  resources:
  - freyrs/status
  verbs:
  - get
