---

# Prometheus ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-configmap
data:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: dsprometheus
        url: http://prometheus-service.telemetry.svc.cluster.local:9090
        isDefault: false
        access: proxy
        editable: true
      - name: Jaeger
        type: jaeger
        uid: dsjaeger
        url: http://jaeger-service.telemetry.svc.cluster.local:16686
        isDefault: false
        access: proxy
        editable: true

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: grafana
          image: grafana/grafana:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: atlassian
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: atlass1an
            - name: GF_SERVER_HTTP_PORT
              value: "80"

          ports:
            - containerPort: 80
              name: http-grafana
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /robots.txt
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            httpGet:
              path: /robots.txt
              port: 80
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-pv
            - name: grafana-provision
              mountPath: /etc/grafana/provisioning/datasources
      volumes:
        - name: grafana-pv
          persistentVolumeClaim:
            claimName: grafana-pvc
        - name: grafana-provision
          configMap:
            name: grafana-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  annotations:
    cloud.google.com/neg: '{"ingress": true, "exposed_ports": {"80":{}}}'
spec:
  selector:
    app: grafana
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80

---

kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: monitoring-route
spec:
  parentRefs:
    - kind: Gateway
      name: grafana-gw2
  hostnames:
    - operator-grafana.fmtl.au
  rules:
    - backendRefs:
        - name: grafana-service
          port: 80

---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: grafana-hcp
spec:
  default:
    logConfig:
      enabled: true
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /robots.txt
  targetRef:
    group: ""
    kind: Service
    name: grafana-service
