apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: telemetry
resources:
  - namespace.yaml
  - gateway.yaml
  - prometheus.yaml
  - jaeger.yaml
  - otel-collector.yaml
  - grafana.yaml
