[tools]
go = "1.22.0"


[tasks.deploy_operator]
description = 'Deploy the Freyr Operator'
env={NAMESPACE= 'freyr-system', KEYFILE= '../secrets/freyr-operator-b9bde5075a35.json'}
run = """
make deploy

kubectl create secret docker-registry gcr-json-key \
		--docker-server=australia-southeast2-docker.pkg.dev \
		--docker-username=_json_key \
		--docker-password="$(cat ${KEYFILE})" \
		-n ${NAMESPACE}
kubectl patch -n ${NAMESPACE} serviceaccount freyr-controller-manager -p '{"imagePullSecrets": [{"name": "gcr-json-key"}]}'

echo "Waiting for the operator to be ready"
sleep 5
POD=$(kubectl get pods -n ${NAMESPACE} -l control-plane=controller-manager -o jsonpath='{.items[0].metadata.name}')
echo purging ${POD}
kubectl delete pods -n ${NAMESPACE} -l control-plane=controller-manager
"""

[tasks.namespace_setup]
env={NAMESPACE= 'default', KEYFILE= '../secrets/freyr-operator-b9bde5075a35.json'}
description = 'Initialize the namespace for testing'
run = """
kubectl create namespace ${NAMESPACE}
kubectl create secret docker-registry gcr-json-key \
		--docker-server=australia-southeast2-docker.pkg.dev \
		--docker-username=_json_key \
		--docker-password="$(cat ${KEYFILE})" \
		-n ${NAMESPACE}
kubectl patch -n ${NAMESPACE} serviceaccount default -p '{"imagePullSecrets": [{"name": "gcr-json-key"}]}'
kubens ${NAMESPACE}
"""

[tasks.namespace_destroy]
env={NAMESPACE= 'operator-testing'}
description = 'Initialize the namespace for testing'
run = """
kubectl delete namespace ${NAMESPACE}
kubens default
"""

[tasks.demo_deploy]
env={NAMESPACE= 'default'}
description = 'Deploy Demo'
run = """
kubectl -n ${NAMESPACE} apply -k config/samples
"""

[tasks.demo_destroy]
env={NAMESPACE= 'default'}
description = 'Deploy Demo'
run = """
kubectl -n ${NAMESPACE}  delete -k config/samples
"""
