apiVersion: freyr.fmtl.au/v1alpha1
kind: Freyr
metadata:
  name: demo
spec:
  mode: trig
  trig:
    duration: 600s
    min: 1
    max: 16
  envs:
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector-service.telemetry.svc.cluster.local:4318/"
