apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "freyr.fmtl.au/v1alpha1",
          "kind": "Operator",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "op-freyr",
              "app.kubernetes.io/instance": "operator-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "operator",
              "app.kubernetes.io/part-of": "op-freyr"
            },
            "name": "operator-sample"
          },
          "spec": {
            "mode": "weather",
            "weather": {
              "apiKey": "e6026d8715d3749e856387417bf5ded9",
              "city": "Melbourne",
              "country": "AU"
            }
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2024-02-13T10:31:08Z"
    operators.operatorframework.io/builder: operator-sdk-v1.33.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: op-freyr.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Operator is the Schema for the operators API
      displayName: Operator
      kind: Operator
      name: operators.freyr.fmtl.au
      version: v1alpha1
  description: Freyr is an example Kubernetes Operator, which scales a captain/conscript
    microservice based on the weather
  displayName: freyr
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - freyr.fmtl.au
          resources:
          - operators
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - freyr.fmtl.au
          resources:
          - operators/finalizers
          verbs:
          - update
        - apiGroups:
          - freyr.fmtl.au
          resources:
          - operators/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: op-freyr-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: op-freyr
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: op-freyr
          control-plane: controller-manager
        name: op-freyr-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.14.1
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: australia-southeast2-docker.pkg.dev/freyr-operator/imgs/freyr-operator:latest
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: op-freyr-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: op-freyr-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - freyr
  - captain
  - conscript
  - operator
  links:
  - name: Op Freyr
    url: https://op-freyr.domain
  maintainers:
  - email: nickfmtl.au
    name: nick
  maturity: alpha
  provider:
    name: fmtl.au
    url: fm
  version: 0.0.1
