apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: ship-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Ship is the Schema for the ships API
      displayName: Ship
      kind: Ship
      name: ships.freyr.fmtl.au
      version: v1alpha1
  description: asdasd
  displayName: ship-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ship
  - operator
  - demo
  links:
  - name: Ship Operator
    url: https://ship-operator.domain
  maturity: alpha
  provider:
    name: fmtl.au
  version: 0.0.0
