kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: operator-route
  namespace: ship-operator
spec:
  parentRefs:
    - name: cluster-gw
      namespace: nginx-gateway
      sectionName: http
  hostnames:
    - operator.fmtl.au
  rules:
    - backendRefs:
        - name: black-pearl
          port: 80
