apiVersion: freyr.fmtl.au/v1alpha1
kind: Ship
metadata:
  name: black-pearl
  namespace: ship-operator
spec:
  captain:
    image: australia-southeast2-docker.pkg.dev/freyr-operator/imgs/captain:demo
  mode: trig
  trig:
    duration: 300s
    min: 5
    max: 15
  envs:
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel.telemetry.svc.cluster.local:4318"
