[env]
file="freyr-operator-b9bde5075a35.json"

[tasks.enc]
description= "Encrypt a file"
run = """
openssl enc -aes-256-cbc -a -salt -in ${file} -out file.enc
"""

[tasks.dec]
description= "Decrypt a file"
run = """
openssl enc -d -aes-256-cbc -a -in file.enc -out ${file}
"""
