
docker.build:
	docker build -t freyr/conscript .

docker.push:
	docker tag freyr/conscript australia-southeast2-docker.pkg.dev/freyr-operator/imgs/conscript:latest
	docker push australia-southeast2-docker.pkg.dev/freyr-operator/imgs/conscript:latest